name: Deploy to Beget
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r HelloDjango/requirements.txt

      - name: Collect static files
        run: python /HelloDjango/manage.py collectstatic --noinput

      - name: Deploy to Beget
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          key: ${{ secrets.BEGET_SSH_KEY }}
          source: .
          target: ${{ vars.BEGET_TARGET }}
          args: -r